<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWPF>true</UseWPF>
        <ImplicitUsings>enable</ImplicitUsings>
        <AssemblyName>Qenex.QSuite.Common.InpBindingManager</AssemblyName>
        <RootNamespace>Qenex.QSuite.Common.InpBindingManager</RootNamespace>
    </PropertyGroup>

</Project>
