<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>Qenex.QSuite.Scripting.PythonScript</AssemblyName>
        <RootNamespace>Qenex.QSuite.Scripting.PythonScript</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Script\Script.csproj" />
    </ItemGroup>

</Project>
