<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0-windows7.0</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWPF>true</UseWPF>
        <ImplicitUsings>enable</ImplicitUsings>
        <AssemblyName>Qenex.QSuite.Controls.SignalControl</AssemblyName>
        <RootNamespace>Qenex.QSuite.Controls.SignalControl</RootNamespace>
        <Company>Qenex.QSuite.Controls.SignalControl</Company>
        <Product>Qenex.QSuite.Controls.SignalControl</Product>
    </PropertyGroup>

    <ItemGroup>
      <None Remove="Icons\SIngleSignalControl.png" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Models\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Common\WpfComm\WpfComm.csproj" />
      <ProjectReference Include="..\..\Variables\QVariables\QVariables.csproj" />
      <ProjectReference Include="..\Control\Control.csproj" />
      <ProjectReference Include="..\DerivedWinControls\DerivedWinControls.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Qenex.QLibs.QUI" Version="1.0.10" />
      <PackageReference Include="Telerik.Windows.Controls.for.Wpf" Version="2026.1.415" />
      <PackageReference Include="Telerik.Windows.Controls.Navigation.for.Wpf" Version="2026.1.415" />
    </ItemGroup>

    <ItemGroup>
      <Resource Include="Icons\SIngleSignalControl.png" />
    </ItemGroup>

</Project>
