<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWPF>true</UseWPF>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Qenex.QSuite.Controls.GraphControl</RootNamespace>
        <AssemblyName>Qenex.QSuite.Controls.GraphControl</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Qenex.QLibs.QUI" Version="1.0.9" />
      <PackageReference Include="ScottPlot.WPF" Version="5.1.57" />
      <PackageReference Include="Telerik.Windows.Controls.for.Wpf" Version="2025.4.1111" />
      <PackageReference Include="Telerik.Windows.Controls.GridView.for.Wpf" Version="2025.4.1111" />
      <PackageReference Include="Telerik.Windows.Controls.Navigation.for.Wpf" Version="2025.4.1111" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Common\WpfComm\WpfComm.csproj" />
      <ProjectReference Include="..\Control\Control.csproj" />
      <ProjectReference Include="..\DerivedWinControls\DerivedWinControls.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Icons\GraphControl.png" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Icons\RtGraphControl.png" />
    </ItemGroup>

    <ItemGroup>
      <Resource Include="Icons\GraphControl.png" />
    </ItemGroup>

</Project>
