<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWPF>true</UseWPF>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Qenex.QSuite.Controls.GraphControl</RootNamespace>
        <AssemblyName>Qenex.QSuite.Controls.GraphControl</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.142" />
      <PackageReference Include="Qenex.QLibs.QUI" Version="1.0.9" />
      <PackageReference Include="ScottPlot.WPF" Version="5.1.58" />
      <PackageReference Include="Telerik.Windows.Controls.for.Wpf" Version="2026.1.415" />
      <PackageReference Include="Telerik.Windows.Controls.GridView.for.Wpf" Version="2026.1.415" />
      <PackageReference Include="Telerik.Windows.Controls.Input.for.Wpf" Version="2026.1.415" />
      <PackageReference Include="Telerik.Windows.Controls.Navigation.for.Wpf" Version="2026.1.415" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Common\WpfComm\WpfComm.csproj" />
      <ProjectReference Include="..\Control\Control.csproj" />
      <ProjectReference Include="..\DerivedWinControls\DerivedWinControls.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Icons\GraphControl.png" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Icons\RtGraphControl.png" />
    </ItemGroup>

    <ItemGroup>
      <Resource Include="Icons\GraphControl.png" />
    </ItemGroup>

</Project>
