<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>Qenex.QSuite.Common.QClassExt</AssemblyName>
        <RootNamespace>Qenex.QSuite.Common.QClassExt</RootNamespace>
    </PropertyGroup>

</Project>
