<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Qenex.QSuite.Controls.$(MSBuildProjectName)</AssemblyName>
    <RootNamespace>Qenex.QSuite.Controls.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Qenex.QLibs.QUI" Version="1.0.9" />
    <PackageReference Include="Telerik.Windows.Controls.Diagrams.for.Wpf" Version="2025.4.1111" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Protocols\Protocol\Protocol.csproj" />
  </ItemGroup>

</Project>
