<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWPF>true</UseWPF>
        <ImplicitUsings>enable</ImplicitUsings>
        <AssemblyName>Qenex.QSuite.Controls.Control</AssemblyName>
        <RootNamespace>Qenex.QSuite.Controls.Control</RootNamespace>
        <AssemblyVersion>1.0.0</AssemblyVersion>
        <FileVersion>1.0.0</FileVersion>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Variables\QVariables\QVariables.csproj" />
    </ItemGroup>

</Project>
